name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Oliver-Norton10
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2339FF14&color_dots=%23161b22,%230d3d1f,%231a6b32,%2323a648,%2339ff14&color_background=%230D1117

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
